### ISSUE TITLE
docker 网络模式必须是host吗?

### ISSUE THREAD

**Issue by weigeloveu** [sleikang/media_server_tools#54]
1.用的docker compose default网络,启动起来发现后台一点日志输出也没有,是因为网络没用host的原因吗
2.nastool跟jellyfin都搭建在同一个default网络之下,如果不用host,请问这样还需要映射端口吗?
```
version: "3"
services:
  MediaServerTools:
    container_name: MediaServerTools
    volumes:
      - /volume1/docker/MediaServerTools:/config
      略
    environment:
        - TZ=Asia/Shanghai
        - PUID=1026
        - PGID=100
        - UMASK=022
        - MediaServerTools_AUTO_UPDATE=true # 自动更新
        - MediaServerTools_CN_UPDATE=true # 使用国内源更新
    logging:
      driver: json-file
      options:
        max-size: 5m
    image: 'ddsderek/mediaservertools:latest'

  nas-tools:
    image: nastool/nas-tools:latest
    ports:
      - 3000:3000
    volumes:
      - /volume1/docker/nastools:/config
      略
    environment:
      - PUID=1026 # 想切换为哪个用户来运行程序，该用户的uid
      - PGID=100 # 想切换为哪个用户来运行程序，该用户的gid
      - UMASK=000 # 掩码权限，默认000，可以考虑设置为022
      - NASTOOL_AUTO_UPDATE=false # 如需在启动容器时自动升级程程序请设置为true
      - NASTOOL_CN_UPDATE=false # 如果开启了容器启动自动升级程序，并且网络不太友好时，可以设置为true，会使用国内源进行软件更新
      #- REPO_URL=https://ghproxy.com/https://github.com/NAStool/nas-tools.git # 当你访问github网络很差时，可以考虑解释本行注释
      - TZ=Asia/Shanghai # 时区
    restart: always
    hostname: nas-tools
    container_name: nas-tools
```

**Comment by sleikang** [comment]
可以尝试下新版，看你的映射目录时群晖，我这边测试是正常的 
```
version: '3'

services:
  jd_server:
    image: sleikang/media_server_tools:latest
    container_name: media_server_tools
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /volume1/docker/media_server_tools/log:/app/log
      - /volume1/docker/media_server_tools/config:/app/config
    restart: always

```
